FROM node:alpine

WORKDIR /app

COPY ./package.json .
RUN npm install

#Removing copy since  docker-compose.yml refers to the files outside container after mapping using volumes.
#COPY . .

CMD ["npm", "run", "start"]